# Change these first
owner: Travelonux # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Landing
    url: https://travelonux.com

  - name: MeVuelo
    url: https://www.mevuelo.com

  - name: MeVuelo UY
    url: https://www.mevuelo.com.uy
  - name: Admin MeVuelo UY
    url: https://admin.mevuelo.com.uy
    
  - name: MeVuelo UY (testing)
    url: https://mv-uruguay-testing.travelonux.com
  - name: Admin MeVuelo UY (testing)
    url: https://admin-mv-uruguay-testing.travelonux.com

  - name: MeVuelo PY
    url: https://www.mevuelo.com.py
  - name: Admin MeVuelo PY
    url: https://admin.mevuelo.com.py
    
  - name: MeVuelo PY (testing)
    url: https://mv-paraguay-testing.travelonux.com
  - name: Admin MeVuelo PY(testing)
    url: https://admin-mv-paraguay-testing.travelonux.com

  - name: MeVuelo BO
    url: https://www.mevuelo.com.bo
  - name: Admin MeVuelo BO
    url: https://admin.mevuelo.com.bo
    
  - name: MeVuelo BO (testing)
    url: https://mv-bolivia-testing.travelonux.com
  - name: Admin MeVuelo BO(testing)
    url: https://admin-mv-bolivia-testing.travelonux.com
   
  - name: MeVuelo CO
    url: https://www.mevuelo.com.co
  - name: Admin MeVuelo CO
    url: https://admin.mevuelo.com.co
  
  - name: MeVuelo CO (testing)
    url: https://mv-colombia-testing.travelonux.com
  - name: Admin MeVuelo CO (testing)
    url: https://admin-mv-colombia-testing.travelonux.com
    
  - name: Power (production)
    url: https://power.mevuelo.com
  - name: Power (testing)
    url: https://power-testing.travelonux.com

  - name: MeVuelo Core API (production)
    url: https://api.core.production.travelonux.com/status
  - name: MeVuelo Flights API (production)
    url: https://api.flights.production.travelonux.com/status
  - name: MeVuelo Internal Flights API (production)
    url: https://api.internal-flights.production.travelonux.com/status    
  - name: MeVuelo Hotels API (production)
    url: https://api.hotels.production.travelonux.com/status
  - name: MeVuelo Hotels Proxy API (production)
    url: https://api.hotels-proxy.production.travelonux.com/status    
  - name: MeVuelo Packages API (production)
    url: https://api.packages.production.travelonux.com/status
  - name: MeVuelo CRM API (production)
    url: https://api.crm.production.travelonux.com/healthcheck
  - name: MeVuelo Destinations API (production)
    url: https://destinations-cms.production.travelonux.com
    
  - name: MeVuelo Core API (testing)
    url: https://api.core.testing.travelonux.com/status
  - name: MeVuelo Flights API (testing)
    url: https://api.flights.testing.travelonux.com/status
  - name: MeVuelo Internal Flights API (testing)
    url: https://api.internal-flights.testing.travelonux.com/status        
  - name: MeVuelo Hotels API (testing)
    url: https://api.hotels.testing.travelonux.com/status
  - name: MeVuelo Hotels Proxy API (testing)
    url: https://api.hotels-proxy.testing.travelonux.com/status    
  - name: MeVuelo Packages API (testing)
    url: https://api.packages.testing.travelonux.com/status
  - name: MeVuelo CRM API (testing)
    url: https://api.crm.testing.travelonux.com/healthcheck
  - name: MeVuelo Destinations API (testing)
    url: https://destinations-cms.testing.travelonux.com
    
  - name: MeVuelo Packages Availability (MVD - Mobile)
    url: https://api.packages.production.travelonux.com/v1/mevuelo/frontend/packages/healthcheck?departure=MVD&api_key=60f8b35a-2e1e-48d3-939f-41dece9aa5d4&resolution=1
  - name: MeVuelo Packages Availability (ASU - Mobile)
    url: https://api.packages.production.travelonux.com/v1/mevuelo/frontend/packages/healthcheck?departure=ASU&api_key=ebfc5bcd-c798-4a53-a45a-5118f8a1e377&resolution=1

assignees:
  - Cinolkis

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: sites-status.travelonux.com
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
