# Change these first
owner: Travelonux # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Landing
    url: https://travelonux.com

  - name: MeVuelo
    url: https://www.mevuelo.com

  - name: MeVuelo UY
    url: https://www.mevuelo.com.uy
  - name: Admin MeVuelo UY
    url: https://admin.mevuelo.com.uy
    
  - name: MeVuelo UY (testing)
    url: https://mv-uruguay-testing.travelonux.com
  - name: Admin MeVuelo UY (testing)
    url: https://admin-mv-uruguay-testing.travelonux.com

  - name: MeVuelo PY
    url: https://www.mevuelo.com.py
  - name: Admin MeVuelo PY
    url: https://admin.mevuelo.com.py
    
  - name: MeVuelo PY (testing)
    url: https://mv-paraguay-testing.travelonux.com
  - name: Admin MeVuelo PY(testing)
    url: https://admin-mv-paraguay-testing.travelonux.com

  - name: MeVuelo BO
    url: https://www.mevuelo.com.bo
  - name: Admin MeVuelo BO
    url: https://admin.mevuelo.com.bo
    
  - name: MeVuelo BO (testing)
    url: https://mv-bolivia-testing.travelonux.com
  - name: Admin MeVuelo BO(testing)
    url: https://admin-mv-bolivia-testing.travelonux.com
   
  - name: MeVuelo CO
    url: https://www.mevuelo.com.co
  - name: Admin MeVuelo CO
    url: https://admin.mevuelo.com.co
  
  - name: MeVuelo CO (testing)
    url: https://mv-colombia-testing.travelonux.com
  - name: Admin MeVuelo CO (testing)
    url: https://admin-mv-colombia-testing.travelonux.com
    
  - name: Power (production)
    url: https://power.mevuelo.com
  - name: Power (testing)
    url: https://power-testing.travelonux.com

  - name: MeVuelo Core API (production) EKS
    url: https://api.core.mevuelo.com/status

  - name: MeVuelo Flights API (production) EKS
    url: https://api.flights.mevuelo.com/status

  - name: MeVuelo Hotels API (production) EKS
    url: https://api.hotels.mevuelo.com/status

  - name: MeVuelo Hotels Proxy API (production) EKS
    url: https://api.hotels-proxy.mevuelo.com/status

  - name: MeVuelo Packages API (production) EKS
    url: https://api.packages.mevuelo.com/status

  - name: MeVuelo CRM API (production) EKS
    url: https://api.crm.mevuelo.com/healthcheck

  - name: MeVuelo Destinations API (production) EKS
    url: https://destinations-cms.mevuelo.com

  - name: MeVuelo Core API (testing) EKS
    url: https://api.core.eks.testing.travelonux.com/status
  - name: MeVuelo Core API (testing)

  - name: MeVuelo Flights API (testing) EKS
    url: https://api.flights.eks.testing.travelonux.com/status
  - name: MeVuelo Flights API (testing)

  - name: MeVuelo Hotels API (testing) EKS
    url: https://api.hotels.eks.testing.travelonux.com/status

  - name: MeVuelo Hotels Proxy API (testing) EKS
    url: https://api.hotels-proxy.eks.testing.travelonux.com/status

  - name: MeVuelo Packages API (testing) EKS
    url: https://api.packages.eks.testing.travelonux.com/status

  - name: MeVuelo CRM API (testing) EKS
    url: https://api.crm.eks.testing.travelonux.com/healthcheck

  - name: MeVuelo Destinations API (testing) EKS
    url: https://destinations-cms.eks.testing.travelonux.com

  - name: MeVuelo Sales Order (testing) EKS
    url: https://api.sales-order.eks.testing.travelonux.com/healthcheck
    
  - name: MeVuelo Packages Availability (MVD - Mobile)
    url: https://api.packages.mevuelo.com/v1/mevuelo/frontend/packages/healthcheck?departure=MVD&api_key=60f8b35a-2e1e-48d3-939f-41dece9aa5d4&resolution=1
  - name: MeVuelo Packages Availability (TODOS - Mobile)
    url: https://api.packages.mevuelo.com/v1/mevuelo/frontend/packages/healthcheck?departure=TODOS&api_key=60f8b35a-2e1e-48d3-939f-41dece9aa5d4&resolution=1
  - name: MeVuelo Packages Availability (BOG - Mobile)
    url: https://api.packages.mevuelo.com/v1/mevuelo/frontend/packages/healthcheck?departure=BOG&api_key=fc3394e4-1c2d-11ed-861d-0242ac120002&resolution=1
  - name: MeVuelo Packages Availability (TODOS - Mobile)
    url: https://api.packages.mevuelo.com/v1/mevuelo/frontend/packages/healthcheck?departure=TODOS&api_key=fc3394e4-1c2d-11ed-861d-0242ac120002&resolution=1
  - name: MeVuelo Packages Availability (ASU - Mobile)
    url: https://api.packages.mevuelo.com/v1/mevuelo/frontend/packages/healthcheck?departure=ASU&api_key=ebfc5bcd-c798-4a53-a45a-5118f8a1e377&resolution=1
  - name: MeVuelo Packages Availability (TODOS - Mobile)
    url: https://api.packages.mevuelo.com/v1/mevuelo/frontend/packages/healthcheck?departure=TODOS&api_key=ebfc5bcd-c798-4a53-a45a-5118f8a1e377&resolution=1
  - name: MeVuelo Packages Availability (VVI - Mobile)
    url: https://api.packages.mevuelo.com/v1/mevuelo/frontend/packages/healthcheck?departure=VVI&api_key=8f41e23a-b78f-4222-83f6-803eb132ad33&resolution=1
  - name: MeVuelo Packages Availability (TODOS - Mobile)
    url: https://api.packages.mevuelo.com/v1/mevuelo/frontend/packages/healthcheck?departure=TODOS&api_key=8f41e23a-b78f-4222-83f6-803eb132ad33&resolution=1
  - name: MeVuelo Packages Availability Tienda Naranja (ASU - Mobile)
    url: https://api.packages.mevuelo.com/v1/mevuelo/frontend/packages/healthcheck?departure=ASU&api_key=6ff34ba1-d58b-4dfe-af2e-cc234c832ad0&resolution=1
  - name: MeVuelo Packages Availability Tienda Naranja (TODOS - Mobile)
    url: https://api.packages.mevuelo.com/v1/mevuelo/frontend/packages/healthcheck?departure=TODOS&api_key=6ff34ba1-d58b-4dfe-af2e-cc234c832ad0&resolution=1

assignees:
  - Cinolkis

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: sites-status.travelonux.com
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
